Change it to use cmake in the BUILDROOT path so it compiles
When listing four providers other JSS I get the list of capabilities.
For the Mozilla-JSS provider it fails as follows:

java  -classpath .:/home/emaldonado/buildjss/jss/cmake/jss4.jar:/usr/share/java/slf4j/api.jar Lister Mozilla-JSS
Listing: Mozilla-JSS
Mozilla-JSS not found, will try to install it

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.SecurityException: Unable to initialize security library
	at org.mozilla.jss.CryptoManager.initializeAllNative2(Native Method)
	at org.mozilla.jss.CryptoManager.initialize(CryptoManager.java:473)
	at org.mozilla.jss.CryptoManager.initialize(CryptoManager.java:434)
	at Lister.listThem(Lister.java:51)
	at Lister.main(Lister.java:86)